[build]
  command = "echo 'No build needed'"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/mobile/*"
  to = "/mobile/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "node server.js"
  port = 5000
  targetPort = 5000
  publish = "."
  autoLaunch = true
